### ISSUE TITLE
Links to QGIS Project blog posts in https://qgis.org/feeds/qgisplanet.atom news feed use http:// protocol instead of https://

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/qgis-feed#12]
In the https://qgis.org/feeds/qgisplanet.atom news feed, the QGIS Project blog posts are linked using the http:// protocol instead of the https:// one.
The other blog posts in the same feed use the https:// protocol.

Please make the links to the QGIS Project blog posts use the https protocol, too.

**Comment by timlinux** [comment]
I know the name may be a bit misleading, but this repo contains only logic for the News Feed which shows in QGIS. Could you raise your issue over at https://github.com/qgis/QGIS-Django rather? Thanks!

**Comment by agiudiceandrea** [comment]
Thanks @timlinux, the issue was already reported https://github.com/qgis/QGIS-Django/issues/85 in https://github.com/qgis/QGIS-Django and mostly fixed (see https://github.com/qgis/QGIS-Django/issues/85#issuecomment-771552320). I forgot to close this issue report.

Anyway I see in https://qgis.org/feeds/qgisplanet.atom the followinq use of http:// instead of https://

`<title>QGIS Planet</title><link href="http://plugins.qgis.org/planet" rel="alternate"></link><link href="http://plugins.qgis.org/planet//feed/rss/" rel="self"></link><id>http://plugins.qgis.org/planet</id>`
