### ISSUE TITLE
We need a beautiful form for creating new feed entries.

### ISSUE THREAD

**Issue by timlinux** [qgis/qgis-feed#18]
📒 **Note:** This is an EPIC ticket - it must be broken out into small individual tasks, each no more than 1 day of work

## Background

At the moment we create new feed entries like this:

![image](https://github.com/qgis/qgis-feed/assets/178003/73e181b5-316f-45dd-955d-3046baf2ebf4)

And they come out in the feed like this:

![image](https://github.com/qgis/qgis-feed/assets/178003/d900d8b2-34a3-4808-8648-bb51a4b31327)

The process of authoring the entry is quite tricky and error prone. And worse, errors, once published, cannot be corrected since the user's QGIS session caches the entries locally.

To address this we would like to develop a front end (non django admin based) view for authoring content with the following capabilities and considerations:

## Workflow

User has a nice login screen if they visit https://feed.qgis.org/manage

We cannot use the root URL because that is where the feed is published.

After logging in with a beautiful login screen branded with out new QGIS branding, they are provided with tools to manage feed items.

- [x] A list of feed items, sortable and filterable by date published, author, language
- [x] A button to create a new feed item - clicking will take you to a blank feed item form
- [x] Clicking on an item on the list will take you to a feed item form
- [x] The feed item form shall display on the left, all the widgets needed to edit the entry, and on the right, a preview of the entry as it will be rendered in QGIS. Any edits made in the form shall immediately update the preview.
- [x] Once a feed item is created or modified, there will be a review step where the user is asked to confirm that they have checked everything carefully
- [x] The form shall implement such checks as needed to ensure the feed item does not cause issues when rendered in QGIS. This shall include
    - [x] Only the following html tags should be allowed; p, strong, italics. These tags should be editable using a rich editor like mcedit, but there should always be a 'raw' view that can be used to check for hidden characters like \r
    - [x] If a link is set, the link should be checked for validity
    - [x] There should be a hard limit on the number of characters allowed this should be configurable in admin. A starting default or 500 characters would be good I think
    - [x] The form must first be placed in a holding area before final submission
    - [x] The form must be approved by someone with an 'approver' role before it is published

## Caution

This feed site is **very** high traffic and no changes can reduce its stability. Any changes must be covered in tests and demonstrated to be robust.

CC @Xpirix

**Comment by haubourg** [comment]
Nice epic! 

I second the requirements in this priority order: 

- a preview of the entry is the first safety guard against typos 
- a confirmation step with a warning if no filter and spatial filter has been set
- I would add the classical wysiwig buttons to add <p> <href> <strong> tags. I have been searching for the right syntax. Alternatively, I would even prefer a markdown editor, which has become a defacto standard. 
- a new feed proposal in the feed area should raise a mail to the admin users with privileges on the django group `qgisfeedentry_authors`. 
- I would create a new permission `qgisfeed | Can publish QGIS feed entry`  so that we can enforce a review workflow

**Comment by Xpirix** [comment]
The requirements are well noted. I will split the ticket into small tasks firstly, add details and size for each of them after that in order to process tasks.

**Comment by timlinux** [comment]
@Xpirix as an additional note, please pay careful attention to the work we are doing here https://blog.qgis.org/2023/10/03/call-for-proposals-qgis-website-overhaul-2023-2024/ and ensure that any front-end UI closely matches the new design aesthetic of QGIS.org.
