### ISSUE TITLE
Use Django class based view

### ISSUE THREAD

**Issue by Xpirix** [qgis/qgis-feed#37]

**Comment by balogun14** [comment]
@Xpirix is this still open i will like to work on this

**Comment by Xpirix** [comment]
@balogun14 Thank you for your interest for this issue. In fact, this ticket is part of the pull request #39 wich is already merged. Please contact @timlinux if you want to contribute.

**Comment by balogun14** [comment]
@timlinux I WILL LIKE TO CONTRIBUTE sir
