### ISSUE TITLE
No CSS

### ISSUE THREAD

**Issue by timlinux** [qgis/qgis-feed#4]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/178003/63638980-3ef33b80-c697-11e9-942e-262ee11124a3.png">

I guess we are missing the collect static step in the deployed image?

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/178003/63638998-75c95180-c697-11e9-8cab-9b33c243a12d.png">

**Comment by timlinux** [comment]
I think we just need to put this block in the SSL section:

```
   	location /static/ {
      		root /shared-volume/;
  	}

  	location /media/ {
      		root /shared-volume/;
  	}
```

**Comment by myarjunar** [comment]
Hi @timlinux, okay I am taking care of it. Thanks!
