### ISSUE TITLE
Different news lists in different QGIS versions installed through OSGeo4W

### ISSUE THREAD

**Issue by anitagraser** [qgis/qgis-feed#54]
In OSGeo install with nightly and 3.28: I get two different news feed lists displayed in the different versions (but the recent projects list is identical and the user profile is also identical `C:\Users\anita\AppData\Roaming\QGIS\QGIS3\profiles\default `) 

![image](https://github.com/qgis/qgis-feed/assets/590385/cf90cf95-50c9-47b8-8281-5978c9a79d7b)

**Comment by Xpirix** [comment]
Dear @anitagraser ,

I tried to reproduce the issue but did not succeed. I get the same news feed list displayed in both QGIS 3.28 and QGIS nightly. I also did the test from Postman and the JSON raw also provides the same list through different QGIS versions.
Maybe this has been resolved in the meantime?

Best regards.

![Capture d’écran 2023-12-30 063430](https://github.com/qgis/qgis-feed/assets/43842786/44a7bd47-c74f-4944-9f3f-8c4795f92a1a)
