### ISSUE TITLE
Feed entry, set spatial filter windows is empty

### ISSUE THREAD

**Issue by haubourg** [qgis/qgis-feed#56]
@Xpirix 
The spatial filter window is empty when I try to submit a new entry. 

I am using firefox 107, but chrome with a fesh profile behaves the same . I saw no error in the web developper console, with adblock / javascript blocker deactivated

![image](https://github.com/qgis/qgis-feed/assets/1629853/8bab28e5-0e9c-4b0c-9016-030e40198586)

**Comment by Xpirix** [comment]
@haubourg ,

Please find the proposed PR addressing this issue at #61

Best regards.
