### ISSUE TITLE
Clarify who are the reviewers for a feed submission

### ISSUE THREAD

**Issue by haubourg** [qgis/qgis-feed#57]
As a feed editor and reviewer for others, I didn't get any notification when a feed entry was submitted. 

As a feed editor, I expect to be able to pick one or several of the django project members with feed edition privileges and that they get a notification.  
This notification should provide a direct link to the feed entry and a message like
"
Title : QGIS feed entry review requested 
body: 
 Hi, 
%submittinguser%  asked you to review the feed entry available at

https://feed.qgis.org/manage/ %feed entry url link%

Your beloved QGIS Feed bot "

**Comment by Xpirix** [comment]
Hello,

Please find the proposed PR for this issue at #62 

Best regards

**Comment by haubourg** [comment]
@Xpirix We just tested the process and it is super cool. However, I didn't receive any mail notification. I created another dummy entry to confirm and no mail this time again. 
I suppose we ne #70 to be merged to have mail sent ?

**Comment by Xpirix** [comment]
@haubourg , Yes, we have created a new email using the GMAIL host as we are experiencing spam issues with `noreply@qgis.org`. The PR #70 once merged and deployed should activate the email-sending feature.
