### ISSUE TITLE
inconsistent numbers in analytics.qgis.org dashboard

### ISSUE THREAD

**Issue by haubourg** [qgis/qgis-feed#79]
Hi @Xpirix ,
I'm not sure where to create this issue, feel free to move it. 

Looking at our analytics dashboard for a qgis conference last week, I found inconsistent - or mis-titled - graphics. 

our monthly total opening is (today ) ~ 15 millions openings. 

The map by country shows - only for France - 28 Millions in the last 30 days.  

Tim gave me access to metabase's backoffice, but I struggle to understand the link between existing graphics and SQL database. I didn't find either by which process the database is filled. 

Could you check this ? Or give me some hints to be able to debug the dashboard with you ?

**Comment by timlinux** [comment]
@haubourg for the dashboard Has can show you how things are linked up with meta base- perhaps best done a screen share session.

**Comment by haubourg** [comment]
@timlinux I duplicated the dashboard in my personal sandbox. I'm starting to get it now. Let's dig in where the issue is. 
I played with superset before and it took some time to adapt my habits

**Comment by haubourg** [comment]
ok found it. The map by country on the last 30 days was not filtering on the last 30 days. Fixing this. 
So total openings per month is around 15 Millions and France  is 1.6 Million, 10% of total openings. 

Before :

After :

**Comment by haubourg** [comment]
fixed
