### ISSUE TITLE
Problem on publishing a new feed item

### ISSUE THREAD

**Issue by mfangain** [qgis/qgis-feed#81]
Hi @Xpirix ,

With @haubourg we try to publish a new feed item on QGIS : https://feed.qgis.org/manage/update/73/
The stream is served by the stream server, but nothing appears on QGIS.

Do you have any idea on what happens?

Thanks.

Marjorie

**Comment by Xpirix** [comment]
@mfangain 

I think this is related to the cache in QGIS. I can see the feed item after switching to a new profile (see screenshot below). 

I think this issue occurs for the following reasons:

- The recent feed https://feed.qgis.org/manage/update/80/ has been published before the feed https://feed.qgis.org/manage/update/73/
- This recent feed has been cached by QGIS and maybe it ignored the feed before
- Only QGIS >= 3.36 supports the feed updates (from non-published to published status for example) according to the following code: https://github.com/qgis/qgis-feed/blob/e8b98bca7ccd2c724e8a8fc30faf31c6c9878e7f/qgisfeedproject/qgisfeed/views.py#L129-L139
- According to this code, QGIS >= 3.36 get the feed that has been modified recently and QGIS < 3.36 get the feed based on the date in published_from. I'm running with QGIS 3.34.1 and the timestamp it sends to request the feed is 1712912405 (12/04/2024).

I think setting the `Publication start` date to a more recent or near future date should make QGIS showing this new feed. 


![image](https://github.com/qgis/qgis-feed/assets/43842786/9ed587ad-a488-455a-b494-41a62623f5ca)

**Comment by mfangain** [comment]
@Xpirix Thank you for the explanation.

Indeed I've created this new feed few weeks ago and we published it this tuesday.
As you told me, I've modified the publication date start and it works now.

So I note that I have to create new feed when I want to publish it and not before ;-)

Thanks a lot.

Marjorie

**Comment by Xpirix** [comment]
@mfangain My pleasure. You can always create a new feed and submit it for approval. But I think the `Publish start` date needs only to be updated right when the approver wants to publish it to make the workaround for QGIS < 3.36 caching.

Best regards,
Lova

**Comment by haubourg** [comment]
Thanks Lova for solving this !

**Comment by Xpirix** [comment]
My pleasure.
